### ISSUE TITLE
Generated static typed keys

### ISSUE THREAD

**Issue by 3lvis** [kostiakoval/AppInfo#2]
# Feature request

I keep my backend base url in my Info plist. It would be awesome if I could get generated static keys based on the values of my plist!

So no more 

``` objc
NSDictionary *infoDictionary = [[NSBundle mainBundle] infoDictionary];
NSString *baseURLString = [infoDictionary valueForKey:@"APIBaseURL"];
```

But instead 

``` swift
AppInfo.APIBaseURL
```

:)

**Comment by kostiakoval** [comment]
This was next step idea. It's hard to type all keys and support them
:+1:

**Comment by 3lvis** [comment]
I guess it could work like https://github.com/paulsamuels/SBConstants

**Comment by kostiakoval** [comment]
Yes I think so, I was thinking exactly about the same place for "Inspiration". 
But I also want to keep static types, so it should detect that this key has  a String or Int value
Do you like idea in general?

**Comment by 3lvis** [comment]
If you can also add that even better!

**Comment by 3lvis** [comment]
Closing old issues, since they might not be relevant.

**Comment by kostiakoval** [comment]
I'm working on it. So I want to reopen it if you don't mind :)

**Comment by 3lvis** [comment]
@kostiakoval could you open a new issue? I want to keep my https://github.com/issues clean

**Comment by kostiakoval** [comment]
Ok :)
